language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: surge
  project: ./build/
  domain: lexbonder-swapi-challenge.surge.sh
  skip-cleanup: true
notifications:
  email: false